//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow {
            get {
                object obj = ResourceManager.GetObject("arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ball {
            get {
                object obj = ResourceManager.GetObject("ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ballPowerBall {
            get {
                object obj = ResourceManager.GetObject("ballPowerBall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blueBrick {
            get {
                object obj = ResourceManager.GetObject("blueBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream BrickNoise {
            get {
                return ResourceManager.GetStream("BrickNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Controls_Title {
            get {
                object obj = ResourceManager.GetObject("Controls_Title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap controlsBorder {
            get {
                object obj = ResourceManager.GetObject("controlsBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream GameOver {
            get {
                return ResourceManager.GetStream("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gameoverTitle {
            get {
                object obj = ResourceManager.GetObject("gameoverTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gamescreenBorder {
            get {
                object obj = ResourceManager.GetObject("gamescreenBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greenBrick {
            get {
                object obj = ResourceManager.GetObject("greenBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap halfBlueBrick {
            get {
                object obj = ResourceManager.GetObject("halfBlueBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap halfGreenBrick {
            get {
                object obj = ResourceManager.GetObject("halfGreenBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap halfRedBrick {
            get {
                object obj = ResourceManager.GetObject("halfRedBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highscoreBorder {
            get {
                object obj = ResourceManager.GetObject("highscoreBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highscoresTitle {
            get {
                object obj = ResourceManager.GetObject("highscoresTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;407&lt;/x&gt;
        ///    &lt;y&gt;132&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;535&lt;/x&gt;
        ///    &lt;y&gt;132&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;211&lt;/x&gt;
        ///    &lt;y&gt;190&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;338&lt;/x&gt;
        ///    &lt;y&gt;190&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;601&lt;/x&gt;
        ///    &lt;y&gt;190&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;730&lt;/x&gt;
        ///    &lt;y&gt;190&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;27&lt;/x&gt;
        ///    &lt;y&gt;251&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level01 {
            get {
                return ResourceManager.GetString("level01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;459&lt;/x&gt;
        ///    &lt;y&gt;3&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;18&lt;/x&gt;
        ///    &lt;y&gt;71&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;239&lt;/x&gt;
        ///    &lt;y&gt;71&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;459&lt;/x&gt;
        ///    &lt;y&gt;71&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;638&lt;/x&gt;
        ///    &lt;y&gt;71&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;906&lt;/x&gt;
        ///    &lt;y&gt;71&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;125&lt;/x&gt;
        ///    &lt;y&gt;129&lt;/y&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level02 {
            get {
                return ResourceManager.GetString("level02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;361&lt;/x&gt;
        ///    &lt;y&gt;111&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;557&lt;/x&gt;
        ///    &lt;y&gt;111&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;251&lt;/x&gt;
        ///    &lt;y&gt;165&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;460&lt;/x&gt;
        ///    &lt;y&gt;165&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;665&lt;/x&gt;
        ///    &lt;y&gt;165&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;50&lt;/x&gt;
        ///    &lt;y&gt;219&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block&gt;
        ///    &lt;x&gt;184&lt;/x&gt;
        ///    &lt;y&gt;219&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level03 {
            get {
                return ResourceManager.GetString("level03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap longPaddle {
            get {
                object obj = ResourceManager.GetObject("longPaddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Lose {
            get {
                return ResourceManager.GetStream("Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream LoseLife {
            get {
                return ResourceManager.GetStream("LoseLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paddle {
            get {
                object obj = ResourceManager.GetObject("Paddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream PaddleNoise {
            get {
                return ResourceManager.GetStream("PaddleNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paddlePowerBall {
            get {
                object obj = ResourceManager.GetObject("paddlePowerBall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pauseBackground {
            get {
                object obj = ResourceManager.GetObject("pauseBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pausedTitle {
            get {
                object obj = ResourceManager.GetObject("pausedTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redBrick {
            get {
                object obj = ResourceManager.GetObject("redBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shieldPowerBall {
            get {
                object obj = ResourceManager.GetObject("shieldPowerBall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shieldPowerUp {
            get {
                object obj = ResourceManager.GetObject("shieldPowerUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smallPaddle {
            get {
                object obj = ResourceManager.GetObject("smallPaddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Title {
            get {
                object obj = ResourceManager.GetObject("Title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap winnerTitle {
            get {
                object obj = ResourceManager.GetObject("winnerTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
